### ISSUE TITLE
Support for CarrierWave 2.2+

### ISSUE THREAD

**Issue by navase** [dwilkie/carrierwave_direct#235]
Starting from CarrierWave 2.2, `extension_whitelist` is deprecated in favor of `extension_allowlist` (https://github.com/carrierwaveuploader/carrierwave/pull/2442). This gem still uses `extension_whitelist` in various places.

When using the `sample_key` helper, it crashes with `undefined method 'extension_whitelist'`, which breaks the fix in #205.

**Comment by p8** [comment]
This should be fixed in: #236
