### ISSUE TITLE
Stopped working with carrierwave 0.6.0

### ISSUE THREAD

**Issue by getcomparisons** [dwilkie/carrierwave_direct#21]
0.6.0 had some breaking changes. For example, the following error occurs:

```
undefined local variable or method `s3_access_policy' for :ImageUploader
```

This is because there is no longer an s3_access_policy.  Not sure if this is the only incompatibility.
