### ISSUE TITLE
NoMethodError (undefined method `has_key?')

### ISSUE THREAD

**Issue by sandiegoscott** [dwilkie/carrierwave_direct#23]
Got local storage working with carrierwave 0.6.1. As soon as I add carrierwave_direct 0.0.5 to my gemset, without changing anything else, I get the following error. Adding the 'fog' gem, setting 'storage :fog', using version 0.0.4--nothing helps.

Started POST "/patients/101/documents" for 127.0.0.1 at 2012-04-04 15:43:13 -0700
Processing by Patients::DocumentsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"NMXO5l1kdcXpgDYbXZMtdz2fuDJKY+kTXJyFux/iEGw=", "document"=>{"description"=>"Document type 1", "location"=>#<ActionDispatch::Http::UploadedFile:0x000001022a7080 @original_filename="Portfolio Totals.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"document[location]\"; filename=\"Portfolio Totals.csv\"\r\nContent-Type: text/csv\r\n", @tempfile=#<File:/var/folders/W7/W7gnIpGEHbS8Tpkaf2MYDk+++TI/-Tmp-/RackMultipart20120404-52517-cw17h6>>}, "commit"=>"Upload document", "patient_id"=>"101"}
  User Load (0.3ms)  SELECT `users`.\* FROM `users` WHERE `users`.`id` = 65 LIMIT 1
  Patient Load (1.4ms)  SELECT `patients`.\* FROM `patients` WHERE `patients`.`id` = 101 LIMIT 1
   (0.6ms)  BEGIN
   (0.4ms)  ROLLBACK
Completed 500 Internal Server Error in 95ms

NoMethodError (undefined method `has_key?' for /uploads/tmp/20120404-1543-52517-5403/Portfolio_Totals.csv:LocationUploader):
  app/controllers/patients/documents_controller.rb:35:in`create'

class Patients::DocumentsController < ApplicationController
  def create
    @document = Document.new(params[:document])
    if @document.save # THIS IS LINE 35
    redirect_to patient_documents_path(@patient, :notice => "Document created.") and return
  else
   # ... setup for new again...
   render :action => "new" and return
 end
end

class Document < ActiveRecord::Base
  belongs_to :patient
  validates_presence_of :description
  mount_uploader :location, LocationUploader
  attr_accessible :patient_id, :description, :location
end

class LocationUploader < CarrierWave::Uploader::Base
  def store_dir
    "uploads/#{model.id}"
  end
end

class CreateDocuments < ActiveRecord::Migration
  def self.up
    create_table :documents do |t|
      t.references  :patient
      t.string      :description, :limit => 40
      t.string      :location
      t.timestamps
    end
  end
end
